// lib/mockData.ts — realistic mock PaceResult for dev/demo mode

import { PaceResult } from '../types';

export const MOCK_PACE_RESULT: PaceResult = {
  session_id: 'demo-session-001',
  diagnostic_required: false,
  cvs_nexus: 2.75,
  cvs_legacy: 1.0,
  current_mastery: [
    {
      esco_uri: 'http://data.europa.eu/esco/skill/S1',
      label: 'Python Programming',
      p_m: 0.85,
      p_l0: 0.80,
      ci_lower: 0.78,
      ci_upper: 0.92,
      ci_color: 'green',
      evidence: '5 years Python development, Django, FastAPI projects',
    },
    {
      esco_uri: 'http://data.europa.eu/esco/skill/S2',
      label: 'SQL & Databases',
      p_m: 0.72,
      p_l0: 0.65,
      ci_lower: 0.61,
      ci_upper: 0.83,
      ci_color: 'green',
      evidence: 'PostgreSQL, query optimization mentioned in resume',
    },
    {
      esco_uri: 'http://data.europa.eu/esco/skill/S3',
      label: 'Machine Learning',
      p_m: 0.45,
      p_l0: 0.30,
      ci_lower: 0.32,
      ci_upper: 0.58,
      ci_color: 'amber',
      evidence: 'Basic ML projects, scikit-learn mentioned',
    },
    {
      esco_uri: 'http://data.europa.eu/esco/skill/S4',
      label: 'Docker & Kubernetes',
      p_m: 0.28,
      p_l0: 0.20,
      ci_lower: 0.15,
      ci_upper: 0.41,
      ci_color: 'red',
      evidence: 'Docker mentioned once, no Kubernetes experience',
    },
    {
      esco_uri: 'http://data.europa.eu/esco/skill/S5',
      label: 'System Design',
      p_m: 0.60,
      p_l0: 0.55,
      ci_lower: 0.48,
      ci_upper: 0.72,
      ci_color: 'amber',
      evidence: 'Microservices architecture in prior role',
    },
    {
      esco_uri: 'http://data.europa.eu/esco/skill/S6',
      label: 'TypeScript & React',
      p_m: 0.55,
      p_l0: 0.50,
      ci_lower: 0.42,
      ci_upper: 0.68,
      ci_color: 'amber',
      evidence: 'React projects mentioned, TypeScript basic usage',
    },
  ],
  target_skills: [
    {
      esco_uri: 'http://data.europa.eu/esco/skill/S1',
      label: 'Python Programming',
      p_m: 0.90,
      p_l0: 0.85,
      ci_lower: 0.85,
      ci_upper: 0.95,
      ci_color: 'green',
      evidence: 'Required: Senior Python Engineer role',
    },
    {
      esco_uri: 'http://data.europa.eu/esco/skill/S2',
      label: 'SQL & Databases',
      p_m: 0.85,
      p_l0: 0.80,
      ci_lower: 0.78,
      ci_upper: 0.92,
      ci_color: 'green',
      evidence: 'Required: complex query optimization',
    },
    {
      esco_uri: 'http://data.europa.eu/esco/skill/S3',
      label: 'Machine Learning',
      p_m: 0.75,
      p_l0: 0.70,
      ci_lower: 0.65,
      ci_upper: 0.85,
      ci_color: 'green',
      evidence: 'Required: ML model deployment',
    },
    {
      esco_uri: 'http://data.europa.eu/esco/skill/S4',
      label: 'Docker & Kubernetes',
      p_m: 0.80,
      p_l0: 0.75,
      ci_lower: 0.70,
      ci_upper: 0.90,
      ci_color: 'green',
      evidence: 'Required: container orchestration',
    },
    {
      esco_uri: 'http://data.europa.eu/esco/skill/S5',
      label: 'System Design',
      p_m: 0.85,
      p_l0: 0.80,
      ci_lower: 0.78,
      ci_upper: 0.92,
      ci_color: 'green',
      evidence: 'Required: distributed systems design',
    },
    {
      esco_uri: 'http://data.europa.eu/esco/skill/S6',
      label: 'TypeScript & React',
      p_m: 0.70,
      p_l0: 0.65,
      ci_lower: 0.60,
      ci_upper: 0.80,
      ci_color: 'green',
      evidence: 'Required: full-stack contribution',
    },
  ],
  path_variants: [
    {
      label: 'Speed',
      lambda_val: 2.0,
      total_hours: 14,
      cvs: 3.2,
      skill_coverage_pct: 78,
      z3_verified: true,
      modules: [
        {
          course_id: 'C001',
          title: 'Docker & Kubernetes Foundations',
          hours: 4,
          teaches: ['http://data.europa.eu/esco/skill/S4'],
          is_mandatory: true,
          bkt_delta: 0.45,
          reward_score: 0.91,
          justification_en:
            'Critical gap: Docker mastery is at 0.28, well below the 0.80 target. This foundational course is mandatory for the role and addresses the highest-priority skill gap.',
          z3_result: 'PASS',
          rejection_reason: null,
        },
        {
          course_id: 'C002',
          title: 'ML Model Deployment in Production',
          hours: 6,
          teaches: ['http://data.europa.eu/esco/skill/S3'],
          is_mandatory: false,
          bkt_delta: 0.28,
          reward_score: 0.84,
          justification_en:
            'Your ML fundamentals are solid at 0.45. This course bridges the gap to 0.75 required mastery with a focus on deployment, not theory you already know.',
          z3_result: 'PASS',
          rejection_reason: null,
        },
        {
          course_id: 'C003',
          title: 'Advanced SQL: Query Optimization',
          hours: 4,
          teaches: ['http://data.europa.eu/esco/skill/S2'],
          is_mandatory: false,
          bkt_delta: 0.15,
          reward_score: 0.76,
          justification_en:
            'SQL mastery at 0.72 needs a focused 4-hour boost to reach the 0.85 target. Covers window functions, CTEs, and execution plans.',
          z3_result: 'PASS',
          rejection_reason: null,
        },
      ],
    },
    {
      label: 'Balance',
      lambda_val: 1.0,
      total_hours: 22,
      cvs: 2.75,
      skill_coverage_pct: 91,
      z3_verified: true,
      modules: [
        {
          course_id: 'C001',
          title: 'Docker & Kubernetes Foundations',
          hours: 4,
          teaches: ['http://data.europa.eu/esco/skill/S4'],
          is_mandatory: true,
          bkt_delta: 0.45,
          reward_score: 0.91,
          justification_en:
            'Critical gap: Docker mastery is at 0.28, well below the 0.80 target. This foundational course is mandatory for the role.',
          z3_result: 'PASS',
          rejection_reason: null,
        },
        {
          course_id: 'C002',
          title: 'ML Model Deployment in Production',
          hours: 6,
          teaches: ['http://data.europa.eu/esco/skill/S3'],
          is_mandatory: false,
          bkt_delta: 0.28,
          reward_score: 0.84,
          justification_en:
            'Bridges ML gap from 0.45 to 0.75 required mastery.',
          z3_result: 'PASS',
          rejection_reason: null,
        },
        {
          course_id: 'C003',
          title: 'Advanced SQL: Query Optimization',
          hours: 4,
          teaches: ['http://data.europa.eu/esco/skill/S2'],
          is_mandatory: false,
          bkt_delta: 0.15,
          reward_score: 0.76,
          justification_en:
            'SQL mastery boost from 0.72 to 0.85 target.',
          z3_result: 'PASS',
          rejection_reason: null,
        },
        {
          course_id: 'C004',
          title: 'Distributed Systems Design Patterns',
          hours: 5,
          teaches: ['http://data.europa.eu/esco/skill/S5'],
          is_mandatory: false,
          bkt_delta: 0.22,
          reward_score: 0.80,
          justification_en:
            'Your system design is at 0.60, good but not senior-level. This course covers distributed consensus, CAP theorem, and real-world patterns.',
          z3_result: 'PASS',
          rejection_reason: null,
        },
        {
          course_id: 'C005',
          title: 'TypeScript & React Advanced Patterns',
          hours: 3,
          teaches: ['http://data.europa.eu/esco/skill/S6'],
          is_mandatory: false,
          bkt_delta: 0.16,
          reward_score: 0.70,
          justification_en:
            'Full-stack contribution requires TypeScript at 0.70. Short focused course on generics, hooks, and state management.',
          z3_result: 'PASS',
          rejection_reason: null,
        },
      ],
    },
    {
      label: 'Depth',
      lambda_val: 0.2,
      total_hours: 38,
      cvs: 2.1,
      skill_coverage_pct: 100,
      z3_verified: true,
      modules: [
        {
          course_id: 'C001',
          title: 'Docker & Kubernetes Foundations',
          hours: 4,
          teaches: ['http://data.europa.eu/esco/skill/S4'],
          is_mandatory: true,
          bkt_delta: 0.45,
          reward_score: 0.91,
          justification_en: 'Mandatory: Critical infrastructure skill.',
          z3_result: 'PASS',
          rejection_reason: null,
        },
        {
          course_id: 'C006',
          title: 'Kubernetes Advanced: Operators & CRDs',
          hours: 6,
          teaches: ['http://data.europa.eu/esco/skill/S4'],
          is_mandatory: false,
          bkt_delta: 0.15,
          reward_score: 0.72,
          justification_en:
            'Deep mastery path includes advanced Kubernetes for production-grade cluster management.',
          z3_result: 'PASS',
          rejection_reason: null,
        },
        {
          course_id: 'C002',
          title: 'ML Model Deployment in Production',
          hours: 6,
          teaches: ['http://data.europa.eu/esco/skill/S3'],
          is_mandatory: false,
          bkt_delta: 0.28,
          reward_score: 0.84,
          justification_en: 'Bridges ML gap from 0.45 to 0.75.',
          z3_result: 'PASS',
          rejection_reason: null,
        },
        {
          course_id: 'C007',
          title: 'MLOps: Monitoring & Drift Detection',
          hours: 5,
          teaches: ['http://data.europa.eu/esco/skill/S3'],
          is_mandatory: false,
          bkt_delta: 0.10,
          reward_score: 0.68,
          justification_en:
            'Production ML requires monitoring pipelines and drift detection. Included in depth path for long-term mastery.',
          z3_result: 'PASS',
          rejection_reason: null,
        },
        {
          course_id: 'C003',
          title: 'Advanced SQL: Query Optimization',
          hours: 4,
          teaches: ['http://data.europa.eu/esco/skill/S2'],
          is_mandatory: false,
          bkt_delta: 0.15,
          reward_score: 0.76,
          justification_en: 'SQL mastery boost to 0.85 target.',
          z3_result: 'PASS',
          rejection_reason: null,
        },
        {
          course_id: 'C004',
          title: 'Distributed Systems Design Patterns',
          hours: 5,
          teaches: ['http://data.europa.eu/esco/skill/S5'],
          is_mandatory: false,
          bkt_delta: 0.22,
          reward_score: 0.80,
          justification_en: 'System design from 0.60 to senior level.',
          z3_result: 'PASS',
          rejection_reason: null,
        },
        {
          course_id: 'C005',
          title: 'TypeScript & React Advanced Patterns',
          hours: 3,
          teaches: ['http://data.europa.eu/esco/skill/S6'],
          is_mandatory: false,
          bkt_delta: 0.16,
          reward_score: 0.70,
          justification_en: 'Full-stack TypeScript mastery.',
          z3_result: 'PASS',
          rejection_reason: null,
        },
        {
          course_id: 'C008',
          title: 'Python Performance Engineering',
          hours: 5,
          teaches: ['http://data.europa.eu/esco/skill/S1'],
          is_mandatory: false,
          bkt_delta: 0.08,
          reward_score: 0.65,
          justification_en:
            'Python is already strong at 0.85 but depth path targets expert-level profiling, async patterns, and C extensions.',
          z3_result: 'PASS',
          rejection_reason: null,
        },
      ],
    },
  ],
  decision_ledger: {
    extraction_model: 'phi-4-mini on groq',
    justification_model: 'qwen-2.5-7b on groq',
    z3_rules_checked: [
      'PREREQUISITE_ORDER',
      'MASTERY_THRESHOLD',
      'COMPLIANCE_MANDATORY',
      'NO_REDUNDANCY',
    ],
    options_considered: [
      { course_id: 'C009', title: 'Python Basics', rejection_reason: 'Mastery already at 0.85, redundant' },
      { course_id: 'C010', title: 'Intro to SQL', rejection_reason: 'Prerequisite already satisfied at 0.72' },
    ],
    bkt_parameters: { p_t: 0.35, p_s: 0.1, p_g: 0.2 },
    masked_actions_blocked: ['C011', 'C012'],
    timestamp: new Date().toISOString(),
  },
};
